# Generated by Django 4.0.6 on 2022-08-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(default=0, max_length=10)),
                ('fecha_registro', models.DateTimeField()),
                ('frecuente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_reserva', models.DateTimeField()),
                ('cantidad_a_pagar', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('ca', 'cancelado'), ('pa', 'pagado'), ('pe', 'pendiente')], default='pe', max_length=2)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_wally.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('fecha_registro', models.DateTimeField()),
                ('idReserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas_wally.reserva')),
            ],
        ),
    ]
