# Generated by Django 4.0.6 on 2022-08-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_wally', '0002_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cancha',
            field=models.CharField(choices=[('1', 'CANCHA 1'), ('2', 'CANCHA 2')], default='1', max_length=1),
        ),
    ]
